Bahmni/openmrs-module-appointments-frontend

ui/.storybook/config.js
ui/.storybook/webpack.config.js
ui/package-lock.json
ui/package.json
ui/react-components/stories/Dropdown.stories.js

I have added [Storybook](https://storybook.js.org/) to view react components that are developed/being developed. 
I used a [custom configuration](https://storybook.js.org/docs/guides/guide-react/#step-3-create-the-config-file) to provide storybook within the `ui` folder by adding config file at `ui/.storybook/config.js`.
I also added `ui/.storybook/webpack.config.js` to add [SASS support ](https://storybook.js.org/docs/configurations/custom-webpack-config/#full-control-mode)to storybook.
I have created a `ui/react-components/stories/Dropdown.stories.js` as an example. The location of the stories can be debated upon if required (stories can be placed anywhere within `react-components` folder, as specified in the `config.js`).

Add react storybook

---

ui/react-components/components/ToggleButton/ToggleButton.jsx
ui/react-components/components/ToggleButton/ToggleButton.module.scss
ui/react-components/components/ToggleButton/ToggleButton.test.jsx
ui/react-components/stories/ToggleButton.stories.js

I have created a base for Toggle Button and added the following props:
*label
*disabled

Add Toggle Button component

---

constants/ng-constants.json
src/controllers/manage/appointmentsCreateController.js
test/controllers/manage/appointmentsCreateController.spec.js
test/ng-test-constants.js

AP-37 | Sukreet | Show all providers if user has 'Appointments: Add Providers` privilege

---

src/controllers/manage/list/appointmentsListViewController.js

[BAH-959](https://bahmni.atlassian.net/browse/BAH-959)

BAH-959 | Sowmika | Deselect the selected appointment when we move from list view to patient search

---

src/controllers/manage/appointmentsManageController.js
test/controllers/manage/appointmentsManageController.spec.js

[BAH-960](https://bahmni.atlassian.net/browse/BAH-960)

BAH-960 | Sowmika | Clicking on AppointmentList Tab changing the view to calendar day view always

---

constants/ng-constants.json
src/controllers/manage/appointmentsCreateController.js
test/controllers/manage/appointmentsCreateController.spec.js
test/ng-test-constants.js

AP-37 | Sukreet | Changes privilege constant used to Invite providers to appointment

---

ui/react-components/components/AddAppointment/AddAppointment.jsx
ui/react-components/components/AddAppointment/AddAppointment.module.scss
ui/react-components/components/AppointmentEditorCommonFieldsWrapper/AppointmentEditorCommonFieldsWrapper.jsx
ui/react-components/components/CalendarPicker/CalendarPicker.jsx
ui/react-components/components/CalendarPicker/CalendarPicker.module.scss
ui/react-components/components/CalendarPicker/CalendarPicker.spec.jsx
ui/react-components/components/DatePicker/DateInput.jsx
ui/react-components/components/DatePicker/DatePicker.jsx
ui/react-components/components/DatePicker/DatePicker.spec.jsx
ui/react-components/components/DatePicker/DatePickerCustomHeader.jsx
ui/react-components/components/DatePicker/DatePickerCustomHeader.module.scss
ui/react-components/components/Dropdown/AsyncDropdown.jsx
ui/react-components/components/Dropdown/Dropdown.jsx
ui/react-components/components/EditAppointment/EditAppointment.jsx
ui/react-components/components/Location/LocationSearch.jsx
ui/react-components/components/Service/ServiceSearch.jsx

Below cards are covered as part of this PR
* https://bahmni.atlassian.net/browse/AP-48
* https://bahmni.atlassian.net/browse/AP-49
* https://bahmni.atlassian.net/browse/AP-50

Vineela, Bindu| AP-48, AP-49, AP-50 | Tab movement and Service error messages and few css changes in recurring appointments UI

---

ui/react-components/components/TabView/TabView.jsx
ui/react-components/components/TabView/TabView.module.scss
ui/react-components/components/TabView/TabView.spec.jsx
ui/react-components/stories/TabView.stories.js

AP - 56 | Nikhil | Angular to React migration - Appointment List Page tab view

---

.github/workflows/validate_pull_request.yml

As part of this PR, A github workflow has been included which will:
`ubuntu-latest` and `nodejs-12` will be used to run above commands.
Once merged we can put this as branch policies as required step.
Tested on my fork. For a sample [see here](https://github.com/mddubey/openmrs-module-appointments-frontend/pull/1).

Add a workflow to validate PRs before merging

---

ui/react-components/components/Location/LocationSearch.jsx
ui/react-components/components/Provider/ProviderSearch.jsx

**As part of this PR following things are done:**
**Yet to be done:**
Related card: https://bahmni.atlassian.net/browse/AP-52

AP-52 | Fix location and patient search

---

config/react-config.json
src/controllers/manage/calendar/appointmentsDayCalendarController.js
src/controllers/manage/list/appointmentsListViewController.js
src/directives/patientSearch.js
test/controllers/manage/calendar/appointmentsDayCalendarController.spec.js
test/directives/patientSearch.spec.js
ui/local-react-config.js
ui/react-components/api/__mocks__/patientApi.js
ui/react-components/api/appointmentsApi.js
ui/react-components/api/patientApi.js
ui/react-components/api/patientApi.spec.js
ui/react-components/components/AddAppointment/AddAppointment.jsx
ui/react-components/components/AddAppointment/AddAppointment.test.jsx
ui/react-components/components/EditAppointment/EditAppointment.jsx
ui/react-components/config.js
ui/react-components/containers/AppointmentContainer.jsx
ui/react-components/mapper/patientMapper.js
ui/reactAngularAdaptor.js

As Part of this PR following feature has been moved to master, Initially done on openmrs branch
- Open calendar view pop up to edit an appointment based on uuid passed as query param ([AP-32](https://bahmni.atlassian.net/browse/AP-32))
- Populate patient in add screen based on url params ([AP-30](https://bahmni.atlassian.net/browse/AP-30))
- Populate patient in list view filter based on url params ([AP-30](https://bahmni.atlassian.net/browse/AP-30))

AP-30 | Migrate features from OpenMRS branch

---

ui/react-components/components/AddAppointment/AddAppointment.jsx
ui/react-components/components/AppointmentEditorFooter/AppointmentEditorFooter.jsx
ui/react-components/components/AppointmentEditorFooter/AppointmentEditorFooter.spec.jsx
ui/react-components/components/Conflicts/Conflicts.jsx
ui/react-components/components/Conflicts/Footer/ConflictsFooter.jsx
ui/react-components/components/Conflicts/Footer/ConflictsFooter.spec.jsx
ui/react-components/components/EditAppointment/EditAppointment.jsx

https://bahmni.atlassian.net/browse/AP-74

Vineela, Bindu, Kirity| AP-74 | Duplicate appointments created when trying to create a single appointment

---

config/ng-config.json
package.json
src/controllers/manage/list/appointmentsListViewController.js
src/views/manage/list/listView.html
ui/package.json

**Ticket:** [BAH-1123](https://bahmni.atlassian.net/browse/BAH-1123)
**Description:**
- Modified patient ID, listed on the Appointments list view, to appear as a link so that the user is able to open the respective patient dashboard
- Patient dashboard URL is configurable
- Link will always open on a new tab/window
- If no patient dashboard URL is configured, previous behavior will be maintained and text will appear without hyperlink

BAH-1123: Patient ID as configurable hyperlink on Appointments List View

---

config/react-config.json
ui/local-react-config.js
ui/react-components/api/patientApi.js
ui/react-components/api/patientApi.spec.js

JIRA - [https://bahmni.atlassian.net/browse/BAH-2341](https://bahmni.atlassian.net/browse/BAH-2341)

BAH-2341 | Enabling Search By Extra Patient Identifiers

---

.github/workflows/deploy_publish.yml

**Description**
This PR is about : 
-  Supporting multi architecture docker image builds.

BAH-2175 | Support multi architecture docker image builds

---

src/styles/appointments/_serviceAppointment.scss
src/styles/bahmni-components/_buttons.scss
src/styles/bahmni-components/_forms.scss
src/views/admin/serviceTypes.html

BAH-1690 | Alignment issue in Appointment scheduling module

---

.github/workflows/deploy_publish.yml
.github/workflows/validate_pull_request.yml

JIRA -> https://bahmni.atlassian.net/browse/BAH-2667

BAH-2667 | Fix GHA for openmrs-module-appointments-frontend repo

---

ui/react-components/utils/AppointmentSMS.js

Removed URL encoding of phone number for sending sms

BAH-2816 | removed encoding for sms phone number

---

ui/react-components/components/AddAppointment/AddAppointment.jsx
ui/react-components/constants.js

Card Ref : https://app.asana.com/0/1204322126657135/1204378118194874/f
Talk thread Ref : https://talk.openmrs.org/t/introducing-appointment-category-in-bahmni-appointments-module/39410

Kavitha | A-1204378118194874 | add waitlist status to dateless appointments

---

ui/react-components/carbon-theme.scss

Fix for this [PR](https://github.com/Bahmni/openmrs-module-appointments-frontend/pull/280)

Kavitha | BAH-3013 | fix missing brace error

---

ui/react-components/components/AppointmentEditorCommonFieldsWrapper/AppointmentEditorCommonFieldsWrapper.jsx
ui/react-components/components/EditAppointment/ComponentsDisableStatus.js
ui/react-components/components/EditAppointment/EditAppointment.jsx
ui/react-components/components/Provider/ProviderSearch.jsx

In the previous PR of edit appointment #281 while editing an awaiting appointment the time is set to a default of moment object. This PR removes those default values.
Asana: [Ref](https://app.asana.com/0/1204322126657135/1204695790272114)

Phani | A-1204695790272114 | Fix. Edit awaiting appointment showing default datetime 

---

i18n/appointments/locale_en.json
ui/i18n/appointments/locale_en.json
ui/react-components/components/AddAppointment/AddAppointment.test.jsx
ui/react-components/utils/ErrorTranslationsUtil.js

[Ashish | Tanya ] Fix. Error message for selecting providers in add appointment.

[Ashish | Tanya ] Fix. Error message for selecting providers

---

ui/react-components/components/DropdownCarbon/Dropdown.jsx

The dropdown for Day/ Week selector was not updating on select. This PR fixes that issue.

Phani | A- 1204696924680628 | Fix dropdown not updating issue for recurring appointment

---

config/ng-config.json
src/app.js
src/controllers/manage/appointmentsManageController.js
src/controllers/manage/list/appointmentsListViewController.js
src/views/manage/list/listView.html
ui/reactAngularAdaptor.js

This PR adds the ability to cancel Waitlist appointments from the Awaiting Appointments page.

Phani | Sowmya| A- 1204750498836114| Ability to cancel waitlist appointment

---

i18n/appointments/locale_en.json
ui/i18n/appointments/locale_en.json
ui/react-components/carbon-theme.scss
ui/react-components/components/AddAppointment/AddAppointment.jsx
ui/react-components/components/DatePickerCarbon/DatePickerCarbon.jsx
ui/react-components/components/EditAppointment/EditAppointment.jsx
ui/react-components/containers/AppointmentContainer.jsx

JIRA link https://bahmni.atlassian.net/browse/BAH-3136
Documentation https://bahmni.atlassian.net/wiki/spaces/BAH/pages/3213033473/Warning+message+when+user+books+appointments+on+holidays+from+Appointments+module

BAH-3136 | Warning message on appointment booking on holidays

---

i18n/appointments/locale_en.json
ui/react-components/components/GridSummary/GridSummary.jsx
ui/react-components/containers/AppointmentSummaryContainer.jsx
ui/reactAngularAdaptor.js

This PR adds the spinner/loading screen to the Appointment Summary page.
[Aasana Ref](https://app.asana.com/0/1204322126657135/1204567746401263)

Phani | A-1204567746401263 | Fix Delay in showing the appointments in the grid

---

src/controllers/manage/list/appointmentsListViewController.js
src/views/manage/list/listView.html

JIRA: https://bahmni.atlassian.net/browse/BAH-3210

BAH-3210 | Adds configAttributes to list view in appointment and awaiting appointment list

---

.github/scripts/transifex.sh
.github/workflows/deploy_publish.yml
.tx/config

Jira -> [BAH-3002](https://bahmni.atlassian.net/browse/BAH-3002)
In this PR, we have added a script that does the following :
Check if Transifex CLI is installed. If not installed, install the latest Transifex CLI.
Check if the transifex config file is present in the repo at root/.tx/config.
Push the translation source file to transifex by running tx push -s.
If a error message is thrown, capture the error.
Additionally, the .tx/config file has been updated to include more resources.

BAH-3002 | Add. Script To Push Translations To Transifex

---

ui/react-components/components/PatientSearch/PatientSearch.jsx
ui/react-components/components/PatientSearch/PatientSearch.spec.jsx

Adds debouncing logic for patient search api

Sowmya | A-1205219676877884 | [Cure Bug] Search by patient id is flaky in add new appointment

---

package-lock.json
package.json
src/directives/patientSearch.js
test/directives/patientSearch.spec.js

https://app.asana.com/0/1204322126657135/1205831568550570
This PR has changes to update normal patient search to lucene search in appointments list view to search by patient ID

Phani / Arjun | A-1205831568550570 | Update to lucene search

---

src/views/manage/calendar/popUp.html

This PR incorporates changes to display appointment location in the pop up opened from calendar view.

BAH-3482 | Show appointment location in appointment popup

---

src/controllers/manage/list/appointmentsListViewController.js
ui/i18n/appointments/locale_en.json
ui/react-components/components/AddAppointment/AddAppointment.jsx
ui/react-components/components/AppointmentCategory/AppointmentCategory.jsx
ui/react-components/components/AppointmentCategory/AppointmentCategory.spec.jsx

JIRA Links: 
https://bahmni.atlassian.net/browse/BAH-3761
https://bahmni.atlassian.net/browse/BAH-3760

[Phani] | [Bugs][BAH-3761,  BAH-3760] | Close Appointment Sidebar after Save & clear filterParams when editing an appointment

---

src/controllers/manage/appointmentsFilterController.js
src/controllers/manage/list/appointmentsListViewController.js
test/controllers/manage/appointmentsFilterController.spec.js

JIRA -> [BAH-4010](https://bahmni.atlassian.net/browse/BAH-4010)
In this PR, the following changes have been added -
1. Fixed Broken Awaiting Appointments Page. 
2. Fixed Awaiting Appointments List to show all waitList appointments

BAH-4010 | Fix. Awaiting Appointments List To Show All WaitList Appointments

---

src/controllers/manage/list/appointmentsListViewController.js
test/controllers/manage/list/appointmentsListViewController.spec.js

JIRA -> [BAH-3058](https://bahmni.atlassian.net/browse/BAH-3058)

BAH-3058 | Fix. Auto Refresh After Status Change

---

package.json
ui/package.json

JIRA -> [BAH-4097](https://bahmni.atlassian.net/browse/BAH-4097)
For Standard Release.

BAH-4097 | Add. Bump Version Number In package.json

---

package.json

BAH-4110 | Add. Bump Version Number In package.json
